version: "3.2"

services:
  api:
    build: ./images/api
    image: x5rrt4393dd/server-api:latest
    ports:
      - 8080:3000
    volumes:
      - ./images/api/src:/usr/app/src
    environment:
      - POSTGRES_HOST=store
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    depends_on:
      store:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail http://localhost:3000/health || exit 1",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - mynetwork
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  store:
    image: postgres:latest
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: "postgres"
    ports:
      - 5432:5432
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  mynetwork:
    driver: bridge
